feat: build and deploy frappe PRs
revant/erpnext_feature_board pull request #20
Opened 2021-06-11 15:53 UTC by revant

2021-06-11 16:20 UTC, Alchez commented on erpnext_feature_board/clients/k8s.py
> +)
You can use the `typing` module to avoid importing this on runtime

```
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # False at runtime, True for static checkers
	from erpnext_feature_board.erpnext_feature_board.doctype.improvement.improvement import (
		Improvement,
	)
```

2021-06-11 16:20 UTC, Alchez requested changes
I'll do a proper review tomorrow

2021-06-11 17:02 UTC, revant commented on erpnext_feature_board/clients/k8s.py
> +)
When I did, It said Improvement missing on line 194

2021-06-12 09:52 UTC, Alchez commented on erpnext_feature_board/clients/k8s.py
> +)
Oh yeah, you'll have to change the Improvement -> "Improvement" for <Py3.8, I think

2021-06-12 09:55 UTC, Alchez commented on erpnext_feature_board/clients/k8s.py
> +		app = app.replace(".git", "")
We could start storing the app name in Improvement directly, to avoid this

2021-06-12 09:55 UTC, Alchez requested changes
I think only the app name needs to be changed

2021-06-12 17:49 UTC, Alchez approved these changes

2021-06-12 17:49 UTC, merged